# Название клавиатуры (будет отображаться в Bluetooth)
CONFIG_ZMK_KEYBOARD_NAME="Corne"

# Настройки сплит-клавиатуры (Левая половина как мастер/Central)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Энергосбережение (обязательно для nice!nano v2, чтобы батарея не садилась)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_USB_INIT_PRIORITY=90
CONFIG_ZMK_BLE_INIT_PRIORITY=90

# Поддержка OLED дисплея (если он у вас распаян)
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

CONFIG_LVGL_DISPLAY_ROTATE_EN=y
CONFIG_LVGL_DISPLAY_ROTATION_90=y
